# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: streamingflow4j.github.io
title: StreamingFlow4J
#email: projetoghostcompany@gmail.com
#author: Ghost Company
description: StreamingFlow4J
copyright: 'Copyright &copy;StreamingFlow4J 2018, Inc. All rights reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
encoding: UTF-8
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: youtube
    url: https://youtu.be/IHu1oKPkuug?list=PLlGdgT4YoKAeTerFXNCwDUbIMGVKinJkt
  - title: github
    url: https://github.com/streamingflow4j
 # - title: linkedin
 #   url: 
