# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: streamingflow4j.github.io
title: StreamingFlow4J
#email: projetoghostcompany@gmail.com
#author: Ghost Company
description: Streaming Flow 4J
copyright: 'Copyright &copy;Streaming Flow 4J 2020, Inc. All rights reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
encoding: UTF-8
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
 #- title: twitter
 #  url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/streamingflow4j
 # - title: linkedin
 #   url: 
